---
name: Build and Push Docker Image to Artifact Registry
on:
  push:
    branches:
      - 'master'
jobs:
  build-push-to-artifact-registry:
    name: 'Build and Push to GCP'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: id-me-hello-world-app
      PROJECT_ID:	id-me-349223
      SERVICE_ACCOUNT: github-actions-service-account@id-me-349223.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER:	projects/61668707706/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-provider

    steps:
    - name: 'Checking out the Master branch'
      uses: actions/checkout@v3

    # Using Workload Identity Federation instead of a long-life Service Account Key for better security
    - name: 'Authenticating to Google Cloud'
      id: 'auth'
      uses: google-github-actions/auth@v0
      with:
        service_account: ${{ env.SERVICE_ACCOUNT }}
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

    - name: 'Setting up the Google Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0

    - name: 'Building the Docker Image'
      run: docker build -t $IMAGE_NAME:latest .

    - name: 'Tagging the Docker Image'
      id: increment-git-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        bash ./scripts/update_git_tag.sh -v patch

    - name: 'Configuring the Docker client'
      run: |-
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: 'Pushing Docker Image to the Artifact Registry'
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/hello-world-app-images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/hello-world-app-images/$IMAGE_NAME:$GIT_TAG
        docker push us-docker.pkg.dev/$PROJECT_ID/hello-world-app-images/$IMAGE_NAME:latest
        docker push us-docker.pkg.dev/$PROJECT_ID/hello-world-app-images/$IMAGE_NAME:$GIT_TAG